name: wp_status_saver
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  permission_handler: ^10.4.1
  image_gallery_saver: ^2.0.2
  video_player: ^2.7.0
  chewie: ^1.5.0
  provider: ^6.0.5
  share_plus: ^7.0.2
  video_thumbnail: ^0.5.3
  win32: ^5.1.0
  google_mobile_ads: ^5.2.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
